name: 1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
      
      
jobs:
  executar:
    runs-on: ubuntu-latest
    steps:

      - name: Acess
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Clone repository
        run: | 
          git clone https://github.com/cronta/1 .
          
          git clone https://github.com/cronta/first
          cd first
          git remote set-url origin https://${{secrets.username1}}:${{secrets.password}}@github.com/cronta/first
          cd ..
          
          git clone https://github.com/cronta/second
          cd second
          git remote set-url origin https://${{secrets.username1}}:${{secrets.password}}@github.com/cronta/second
          cd ..
          
          git clone https://github.com/cronta/third
          cd third
          git remote set-url origin https://${{secrets.username1}}:${{secrets.password}}@github.com/cronta/third
          cd ..

          git config --global user.email ${{secrets.mail}}
          git config --global user.name ${{secrets.username}}
          
      - name: Create something
        run: python script.py
