name: 2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/18 * * * *'

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:

      - name: Acess
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: clone
        run: git clone https://github.com/cronta/2 .

      - name: Dependencies
        run: pip install selenium requests

      - name: Create something
        run: python script.py ${{secrets.users}} ${{secrets.userid}}
