name: "4"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:

      - name: Acess
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: clone
        run: git clone https://github.com/cronta/4 .

      - name: Dependencies
        run: pip install selenium

      - name: setup
        run: chmod 777 geckodriver
      
      - name: Create something
        run: python script.py
