name: Generate activity on this repository

on:
  workflow_dispatch:
  schedule:
    - cron: '* * */10 * *

jobs:
  update-readme:
    
    name: Generate activity on this repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Generate random commit
        run: echo $RANDOM >> README.md

      - name: Commit changes      
        uses: EndBug/add-and-commit@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
